version: "3.8"
services:
  web:
    container_name: some-nginx
    image: nginx:latest
    ports:
      - '8085:80'
    restart: always
  phpmyadmin:
    container_name: some-phpmyadmin
    image: phpmyadmin
    ports:
      - 8086:80
    environment:
      - PMA_ARBITRARY=1
    restart: always